version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: KARE_database
    ports:
      - "5432:5432"
    networks:
      - default

  backend:
    container_name: backend
    build:
      context: ./back-end
    depends_on:
      - postgres
    networks:
      - default

networks:
  default: