version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: KARE_database
    networks:
      - default

  backend:
    container_name: backend
    build:
      context: ./back-end
    depends_on:
      - postgres
    networks:
      - default

  frontend:
    container_name: frontend
    build:
      context: ./front-end
    ports:
      - "80:80"
    networks:
      - default


networks:
  default: